blog_category:
    type: rest
    resource: Puzzle\Api\BlogBundle\Controller\CategoryController
    
blog_article:
    type: rest
    resource: Puzzle\Api\BlogBundle\Controller\ArticleController

blog_archive:
    type: rest
    resource: Puzzle\Api\BlogBundle\Controller\ArchiveController

blog_comment:
    type: rest
    resource: Puzzle\Api\BlogBundle\Controller\CommentController

blog_flash:
    type: rest
    resource: Puzzle\Api\BlogBundle\Controller\FlashController