services:
    # Listener
    papis.event_listener.article:
        class:  Puzzle\Api\BlogBundle\Listener\ArticleListener
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: papis.article.create, method: onCreateArticle }
            - { name: kernel.event_listener, event: papis.article.delete, method: onDeleteArticle }
